server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://IP:PORT/DATA_BASE?autoReconnect=true&rewriteBatchedStatements=true
    username: USER_NAME
    password: PASSWORD
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 100
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.show_sql: true
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  flyway:
    enabled: true
    baseline-on-migrate: false
    url: jdbc:mariadb://localhost:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
    user: USER
    password: PASSWORD
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
      location: upload-path/
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    kr.co.promptech.noticeboard.feign: debug
    ads.client: debug # open feign package 로그를 보기 위함.
    com.client.external: debug
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

jwt:
  secret: SECRET_KEY
  access-token-expiration: 1800000 # 30분(밀리초단위)
  refresh-token-expiration: 2592000000 # 30일(밀리초단위)

external:
  service:
    host: HOST

feign:
  retry:
    period: 10
    max-period: 20
    max-attempt: 3

servicekey:
  SERVICEKEY