### join
POST {{root-path}}/api/auth/join
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "password",
  "name": "donjin",
  "nickname": "dj",
  "birth": "19950515"
}

### login
POST {{root-path}}/api/auth/login
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "password"
}