server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board?autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 100
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.show_sql: true
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  flyway:
    enabled: true
    baseline-on-migrate: false
    url: jdbc:mariadb://localhost:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
    user: root
    password: root
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
      location: upload-path/
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    kr.co.promptech.noticeboard.feign: debug
    ads.client: debug # open feign package 로그를 보기 위함.
    com.client.external: debug
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

jwt:
  secret: mymasterjsonwebtokensecretkeywithdongjinwithhyuntto
  access-token-expiration: 10000 # 10초(밀리초단위)
  refresh-token-expiration: 2592000000 # 30일(밀리초단위)

external:
  service:
    host: https://apis.data.go.kr/B552735

feign:
  retry:
    period: 10
    max-period: 20
    max-attempt : 3

servicekey:
  uv%2FX9jKubRtlJU3O2UQs7cl3898gk5XsWLLU1KlA5h5u8isQKJ7kkdJG7r43IVVvmHno54E%2FGA2djuDmVWPZzQ%3D%3D